# Generated by Django 3.2.6 on 2021-12-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
    ]
