# Generated by Django 3.2.6 on 2021-12-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0005_achivements_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivements',
            name='link',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
