# Generated by Django 3.2.6 on 2021-12-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0007_alter_achivements_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivements',
            name='lt',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
