# Generated by Django 3.2.6 on 2021-12-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0008_achivements_lt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='achivements',
            name='lt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
